.PHONY: clean All

All:
	@echo "----------Building project:[ FirstProject - Release ]----------"
	@cd "FirstProject" && "$(MAKE)" -f  "FirstProject.mk"
clean:
	@echo "----------Cleaning project:[ FirstProject - Release ]----------"
	@cd "FirstProject" && "$(MAKE)" -f  "FirstProject.mk" clean
