.PHONY: clean All

All:
	@echo "----------Building project:[ BasicIO - Release ]----------"
	@cd "BasicIO" && "$(MAKE)" -f  "BasicIO.mk"
clean:
	@echo "----------Cleaning project:[ BasicIO - Release ]----------"
	@cd "BasicIO" && "$(MAKE)" -f  "BasicIO.mk" clean
