.PHONY: clean All

All:
	@echo "----------Building project:[ LanguageBasics - Debug ]----------"
	@cd "LanguageBasics" && "$(MAKE)" -f  "LanguageBasics.mk"
clean:
	@echo "----------Cleaning project:[ LanguageBasics - Debug ]----------"
	@cd "LanguageBasics" && "$(MAKE)" -f  "LanguageBasics.mk" clean
